# Generated by Django 5.1.1 on 2024-12-01 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderitem_price_alter_shopingcart_price'),
        ('payments', '0003_alter_paymentdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.orderdetails'),
        ),
    ]
