# Generated by Django 5.1.1 on 2024-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_of_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
