# Generated by Django 5.1.1 on 2024-09-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_birth_of_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default-avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
