# Generated by Django 5.1.1 on 2024-10-08 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewvideo',
            name='position',
        ),
        migrations.AddField(
            model_name='category',
            name='attribute_groups',
            field=models.ManyToManyField(blank=True, related_name='categories', to='catalog.attributegroup'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='category/category_photos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='product/product_covers/'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='position',
            field=models.CharField(choices=[('center-large', 'CenterLarge'), ('left-small', 'LeftSmall'), ('right-small', 'RightSmall')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewvideo',
            name='video',
            field=models.FileField(upload_to='review_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])]),
        ),
    ]
