# Generated by Django 5.1.1 on 2024-10-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_reviewvideo_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='value',
            field=models.JSONField(max_length=100),
        ),
    ]
