# Generated by Django 5.1.1 on 2024-10-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productattributevalue_value'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('type', 'value'), name='unique_type_value'),
        ),
    ]
