# Generated by Django 5.1.1 on 2024-10-14 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attribute_group',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='order_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='attribute_groups',
            field=models.ManyToManyField(related_name='categories', to='catalog.attributegroup'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category'),
        ),
        migrations.AlterUniqueTogether(
            name='productdetail',
            unique_together={('product', 'order_num')},
        ),
    ]
