# Generated by Django 5.1.1 on 2024-10-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_attribute_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='order_num',
            field=models.PositiveIntegerField(),
        ),
    ]
