# Generated by Django 5.1.1 on 2024-11-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productsku_sku'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviewphoto',
            constraint=models.UniqueConstraint(fields=('review_section', 'order_num'), name='unique_order_num_per_photo_section'),
        ),
        migrations.AddConstraint(
            model_name='reviewtext',
            constraint=models.UniqueConstraint(fields=('review_section', 'order_num'), name='unique_order_num_per_text_section'),
        ),
        migrations.AddConstraint(
            model_name='reviewvideo',
            constraint=models.UniqueConstraint(fields=('review_section', 'order_num'), name='unique_order_num_per_video_section'),
        ),
    ]
