# Generated by Django 5.1.1 on 2024-11-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_reviewphoto_unique_order_num_per_photo_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewphoto',
            name='order_num',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reviewtext',
            name='order_num',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reviewvideo',
            name='order_num',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
