# Generated by Django 5.1.1 on 2024-11-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_reviewphoto_order_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
