# Generated by Django 5.1.1 on 2024-09-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_address_address_alter_address_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.TextField(default='UNKNOWN'),
        ),
    ]
