# Generated by Django 5.1.1 on 2024-09-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_address_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
