# Generated by Django 5.1.1 on 2024-11-18 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_reviewphoto_order_num_and_more'),
        ('orders', '0003_shopingcart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopingcart',
            unique_together={('user', 'product_sku')},
        ),
        migrations.AlterField(
            model_name='shopingcart',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='shopingcart',
            name='product',
        ),
    ]
