# Generated by Django 5.1.1 on 2024-11-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderdetails_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
